#!/bin/sh

set -eu

ROOT="$(dirname "$(readlink -e "$0")")"

down() (
	mkdir -p ~/.cache/up
	wget -nv -NP ~/.cache/up "$1"
	printf '%s/.cache/up/%s' ~ "${1##*/}"
)

apt() (
	sudo apt update -y
	sudo apt upgrade -y
	sudo apt install -y build-essential curl zsh sqlite3 unzip
)

zsh() (
	if [ ! -e ~/.config/zsh ]; then
		ZSH=~/.config/zsh KEEP_ZSHRC=yes RUNZSH=no sh "$(down https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
		mkdir -p ~/.config/zsh/custom/plugins/
	fi
	histdb=.config/zsh/custom/plugins/zsh-histdb
	if [ ! -e ~/"$histdb" ]; then
		git clone https://github.com/larkery/zsh-histdb ~/"$histdb"
	else
		git -C ~/"$histdb" pull
	fi
)

etc() (
	cd "$ROOT"/etc
	for name in *; do
		if [ -d "$name" ]; then
			ln -sf "$ROOT"/etc/"$name" ~/.config/"$name"
		else
			ln -sf "$ROOT"/etc/"$name" ~/."$name"
		fi
	done
)

bin() (
	cd "$ROOT"/bin
	for name in *; do
		ln -sf "$ROOT"/bin/"$name" ~/.local/bin/"$name"
	done
)

pkg() (
	rm -rf ~/.up
	mkdir ~/.up
	cd ~/.up
	# neovim
	tar --directory ~/.up --get --gzip --strip-components=1 -f \
		"$(down https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz)"
	# delta
	tar --directory ~/.up/bin --get --gzip --strip-components=1 -f \
		"$(down https://github.com/dandavison/delta/releases/download/0.15.1/delta-0.15.1-x86_64-unknown-linux-musl.tar.gz)" \
		delta-0.15.1-x86_64-unknown-linux-musl/delta
	# clangd
	unzip -qq "$(down https://github.com/clangd/clangd/releases/download/15.0.6/clangd-linux-15.0.6.zip)"
	rsync -a clangd_*/ .
	rm -rf clangd_* LICENSE.TXT
	# fd
	tar --directory ~/.up/bin --get --gzip --strip-components=1 -f \
		"$(down https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-unknown-linux-musl.tar.gz)" \
		fd-v8.7.0-x86_64-unknown-linux-musl/fd
)

all() {
	apt
	zsh
	etc
	bin
	pkg
}

"$@"
