export PATH=$HOME/.up/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib
export ZSH="$HOME/.config/zsh"
ZSH_THEME=""

fpath+="$HOME/.config/zsh/custom/typewritten"
TYPEWRITTEN_PROMPT_LAYOUT="pure"
TYPEWRITTEN_SYMBOL="$"
TYPEWRITTEN_DISABLE_RETURN_CODE=true
autoload -U promptinit; promptinit
prompt typewritten

HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder
zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git vi-mode ssh-agent)
zstyle :omz:plugins:ssh-agent agent-forwarding yes
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR='nvr -s --remote-wait'
export GIT_EDITOR=$EDITOR
export SVN_EDITOR=$EDITOR
export PAGER='less -FXi'
export LESS="-RQ"

alias tmux='tmux -2'
v() {
  if [ $# -gt 0 ]; then
    if [ -n "$NVIM" ]; then
      nvr --servername "$NVIM" --nostart "$@"
    else
      nvim "$@"
    fi
  else
    if [ -n "$NVIM" ]; then
      printf "unset NVIM and try again\n" >&2
      return 1
    fi
    nvim +term +starti
  fi
}
alias sp='nvr -o'
alias vsp='nvr -O'
alias tabe='nvr -p'
alias vd='nvr -d'
alias vp='nvr -l'
alias a='tput bel'

#eval "$(atuin init zsh)"
